try:
    a=10
    print(a)
    raise ValueError
except:
    print("exception occurs")